[project]
name = "Public-Transport-Planner"
version = "0.1.0"
description = "Backend for the Public Transport Planner application"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard-no-fastapi-cloud-cli]>=0.141.1",
    "psycopg[binary]>=3.3.5",
]

[tool.ruff]
line-length = 120
indent-width = 4

[tool.ruff.lint]
extend-select = ["FAST"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
line-ending = "auto"
skip-magic-trailing-comma = false